<?php

return [
    'login' => 'resources/js/pages/auth/Login.vue',
    'register' => 'resources/js/pages/auth/Register.vue',
    'welcome' => 'resources/js/pages/Welcome.vue',
    'profile' => 'resources/js/pages/settings/Profile.vue',
    'security' => 'resources/js/pages/settings/Security.vue',
    'verify_email' => 'resources/js/pages/auth/VerifyEmail.vue',
    'two_factor_challenge' => 'resources/js/pages/auth/TwoFactorChallenge.vue',
    'confirm_password' => 'resources/js/pages/auth/ConfirmPassword.vue',
    'auth_types' => 'resources/js/types/auth.ts',

    'two_factor_files' => [
        'resources/js/components/ManageTwoFactor.vue',
        'resources/js/components/TwoFactorSetupModal.vue',
        'resources/js/components/TwoFactorRecoveryCodes.vue',
        'resources/js/components/ui/input-otp/index.ts',
        'resources/js/components/ui/input-otp/InputOTP.vue',
        'resources/js/components/ui/input-otp/InputOTPGroup.vue',
        'resources/js/components/ui/input-otp/InputOTPSeparator.vue',
        'resources/js/components/ui/input-otp/InputOTPSlot.vue',
        'resources/js/composables/useTwoFactorAuth.ts',
    ],

    'two_factor_otp_package' => 'vue-input-otp',

    'passkey_files' => [
        'resources/js/components/PasskeyItem.vue',
        'resources/js/components/ManagePasskeys.vue',
        'resources/js/components/PasskeyRegister.vue',
        'resources/js/components/PasskeyVerify.vue',
    ],

    'team_files' => [
        'app/Actions/Teams/CreateTeam.php',
        'app/Concerns/GeneratesUniqueTeamSlugs.php',
        'app/Concerns/HasTeams.php',
        'app/Data/TeamPermissions.php',
        'app/Data/UserTeam.php',
        'app/Enums/TeamPermission.php',
        'app/Enums/TeamRole.php',
        'app/Http/Controllers/Teams/TeamController.php',
        'app/Http/Controllers/Teams/TeamInvitationController.php',
        'app/Http/Controllers/Teams/TeamMemberController.php',
        'app/Http/Middleware/EnsureTeamMembership.php',
        'app/Http/Middleware/SetTeamUrlDefaults.php',
        'app/Http/Requests/Teams/CreateTeamInvitationRequest.php',
        'app/Http/Requests/Teams/DeleteTeamRequest.php',
        'app/Http/Requests/Teams/RespondToTeamInvitationRequest.php',
        'app/Http/Requests/Teams/SaveTeamRequest.php',
        'app/Http/Requests/Teams/UpdateTeamMemberRequest.php',
        'app/Models/Membership.php',
        'app/Models/Team.php',
        'app/Models/TeamInvitation.php',
        'app/Notifications/Teams/TeamInvitation.php',
        'app/Policies/TeamPolicy.php',
        'app/Rules/TeamName.php',
        'app/Rules/UniqueTeamInvitation.php',
        'app/Rules/ValidTeamInvitation.php',
        'database/factories/TeamFactory.php',
        'database/factories/TeamInvitationFactory.php',
        'database/migrations/2026_01_27_000001_create_teams_table.php',
        'database/migrations/2026_01_27_000002_add_current_team_id_to_users_table.php',
        'resources/js/components/CancelInvitationModal.vue',
        'resources/js/components/CreateTeamModal.vue',
        'resources/js/components/DeleteTeamModal.vue',
        'resources/js/components/InviteMemberModal.vue',
        'resources/js/components/LeaveTeamModal.vue',
        'resources/js/components/PendingInvitationsModal.vue',
        'resources/js/components/RemoveMemberModal.vue',
        'resources/js/components/TeamInvitationAlert.vue',
        'resources/js/components/TeamSwitcher.vue',
        'resources/js/pages/teams/Edit.vue',
        'resources/js/pages/teams/Index.vue',
        'resources/js/types/teams.ts',
        'tests/Feature/Teams/PruneExpiredTeamInvitationsTest.php',
        'tests/Feature/Teams/TeamInvitationTest.php',
        'tests/Feature/Teams/TeamMemberTest.php',
        'tests/Feature/Teams/TeamTest.php',
    ],
];
